"""
    Instead of a yaml file, we will just use this python file and record a long list of words
    which are supposed to be polysemous, which we will want to split up
"""

def get_polysemous_splitup_words():
    out = [
        ' attack ',
        ' act ',
        ' die ',
        ' kick ',
        ' sand ',
        ' address ',
        ' aim ',

        ' act ',
        ' address ',
        ' back ',
        ' bear ',
        ' block ',
        ' catch ',
        ' charge ',

        ' crack ',
        ' double ',

        ' face ',
        ' head ',
        ' march ',
        ' order ',

        ' play ',
        ' roll ',
        ' saw ',
        ' tie ',
        ' train ',
        ' treat ',
        ' value ',
        ' visit ',
        ' wake ',
        ' work ',
        ' zone ',

        ' act ',
        ' address ',
        ' aim ',
        ' answer ',
        ' back ',
        ' balloon ',
        ' bank ',
        ' battle ',
        ' bear ',
        ' bend ',
        ' blast ',
        ' block ',
        ' break ',
        ' brush ',
        ' catch ',
        ' challenge ',
        ' charge ',
        ' cheer ',
        ' color ',
        ' cook ',
        ' crack ',
        ' curl ',
        ' cycle ',
        ' dance ',
        ' design ',
        ' die ',
        ' double ',
        ' doubt ',
        ' dust ',
        ' echo ',
        ' end ',
        ' estimate ',
        ' face ',
        ' finish ',
        ' fish ',
        ' flood ',
        ' fool ',
        ' frown ',
        ' garden ',
        ' glue ',
        ' guard ',
        ' guess ',
        ' hammer ',
        ' hand ',
        ' head ',
        ' hug ',
        ' insult ',
        ' iron ',
        ' kiss ',
        ' laugh ',
        ' loan ',
        ' love ',
        ' man ',
        ' march ',
        ' milk ',
        ' object ',
        ' order ',
        ' paddle ',
        ' peel ',
        ' permit ',
        ' play ',
        ' pop ',
        ' practice ',
        ' produce ',
        ' punch ',
        ' question ',
        ' quiz ',
        ' rhyme ',
        ' rock ',
        ' roll ',
        ' run ',
        ' sand ',
        ' saw ',
        ' skate ',
        ' smell ',
        ' surprise ',
        ' thunder ',
        ' tie ',
        ' time ',
        ' toast ',
        ' trace ',
        ' train ',
        ' treat ',
        ' trick ',
        ' use ',
        ' vacuum ',
        ' value ',
        ' visit ',
        ' wake ',
        ' walk ',
        ' water ',
        ' wish ',
        ' work ',
        ' yawn ',
        ' zone ',

        ' cut ',
        ' break ',

        ' well ',
        ' down ',

        ' run ',
        ' round ',
        ' table ',
        ' bank ',
        ' cold ',
        ' good ',
        ' mouse ',
        ' was ',
        ' key ',
        ' arms ',
        ' thought ',
        ' pizza ',
        ' made ',
        ' book ',
        ' damn ',
    ]

    out = sorted(list(set([x.strip() for x in out])))
    return out
